In [1]:
import os
import pandas as pd

In [2]:
lat=pd.read_csv('lat.csv')['Lat']
long=pd.read_csv('long.csv')['Long']

In [3]:
from itertools import product

In [4]:
c = list(product(lat, long))

In [5]:
data=pd.DataFrame(c,columns=['lat','long'])

In [6]:
data

             lat        long
0      33.705431 -119.089550
1      33.705431 -119.075795
2      33.705431 -119.062039
3      33.705431 -119.048284
4      33.705431 -119.034528
5      33.705431 -119.020773
6      33.705431 -119.007018
7      33.705431 -118.993262
8      33.705431 -118.979507
9      33.705431 -118.965751
10     33.705431 -118.951996
11     33.705431 -118.938241
12     33.705431 -118.924485
13     33.705431 -118.910730
14     33.705431 -118.896974
15     33.705431 -118.883219
16     33.705431 -118.869463
17     33.705431 -118.855708
18     33.705431 -118.841953
19     33.705431 -118.828197
20     33.705431 -118.814442
21     33.705431 -118.800686
22     33.705431 -118.786931
23     33.705431 -118.773176
24     33.705431 -118.759420
25     33.705431 -118.745665
26     33.705431 -118.731909
27     33.705431 -118.718154
28     33.705431 -118.704399
29     33.705431 -118.690643
...          ...         ...
11634  34.859747 -118.016628
11635  34.859747 -118.002873
11636  34.859747 -117.989117
11637  34.859747 -117.975362
11638  34.859747 -117.961606
11639  34.859747 -117.947851
11640  34.859747 -117.934096
11641  34.859747 -117.920340
11642  34.859747 -117.906585
11643  34.859747 -117.892829
11644  34.859747 -117.879074
11645  34.859747 -117.865319
11646  34.859747 -117.851563
11647  34.859747 -117.837808
11648  34.859747 -117.824052
11649  34.859747 -117.810297
11650  34.859747 -117.796542
11651  34.859747 -117.782786
11652  34.859747 -117.769031
11653  34.859747 -117.755275
11654  34.859747 -117.741520
11655  34.859747 -117.727764
11656  34.859747 -117.714009
11657  34.859747 -117.700254
11658  34.859747 -117.686498
11659  34.859747 -117.672743
11660  34.859747 -117.658987
11661  34.859747 -117.645232
11662  34.859747 -117.631477
11663  34.859747 -117.617721

[11664 rows x 2 columns]

In [7]:
#cut the lower corner of the rectangular (it's the sea)
data[~((data['lat']<34.001001) & (data['long']<-118.493014))].shape

(10432, 2)

In [8]:
data[~((data['lat']<34.001001) & (data['long']<-118.493014))].to_excel("latlongoutputreduced2.xlsx")